wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1632907641
    t:
      1:
      - 1
      - 5
      4: 3.7.11
      5: 0.12.2
      8:
      - 3
      - 5
